name: Deploy to Development Environment

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install parcel --save-dev

      - name: Build Website
        run: npx parcel build src/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
